Require lat
Output social/render/fzf_embed.gif

Set Theme "Gruvbox Dark"
Set WindowBar Rings
Set BorderRadius 10
Set Margin 10

Set FontSize 32
Set Width 2400
Set Height 1200
Set TypingSpeed 0.2

Type "fzf --preview 'lat -r {}'"
Sleep 1s

Enter
Sleep 2s

Type "main.c"
Sleep 2s
Backspace 7
Sleep 1s

Type "types.h"
Sleep 1s
Backspace 8
Sleep 2s

Type "file.c"
Sleep 3s
Backspace 7
Sleep 2s

Up@3s 15

Sleep 3s

Enter

Sleep 2s
